# Generated by Django 5.2.14 on 2026-05-18 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('brain', 'Brain'), ('heart', 'Heart'), ('briefcase', 'Briefcase'), ('star', 'Star'), ('landmark', 'Landmark'), ('flask', 'Flask')], max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('reading_time', models.IntegerField(default=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='capsules.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
